name: Deploy to GitHub Pages
on:
  push:
    branches:
      - zh-cn
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/docs_requirements.txt

    - name: Build sphinx documentation
      run: |
        cd docs
        make html
        
    - name: Setup github pages domain
      run: |
        touch docs/_build/html/.nojekyll
        echo "${{ secrets.GH_DOMAIN }}" > docs/_build/html/CNAME

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/_build/html
